# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_csiatlante.ui'
#
# Created: Thu Mar 31 11:25:05 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CsiAtlante(object):
    def setupUi(self, CsiAtlante):
        CsiAtlante.setObjectName(_fromUtf8("CsiAtlante"))
        CsiAtlante.resize(461, 458)
        CsiAtlante.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(0, 436))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabProgetti = QtGui.QWidget()
        self.tabProgetti.setObjectName(_fromUtf8("tabProgetti"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabProgetti)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.tabProgetti)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.prj_cboCategory = QtGui.QComboBox(self.tabProgetti)
        self.prj_cboCategory.setObjectName(_fromUtf8("prj_cboCategory"))
        self.horizontalLayout_12.addWidget(self.prj_cboCategory)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.tabProgetti)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.prj_txFiltro = QtGui.QLineEdit(self.tabProgetti)
        self.prj_txFiltro.setObjectName(_fromUtf8("prj_txFiltro"))
        self.horizontalLayout_11.addWidget(self.prj_txFiltro)
        self.prj_btCerca = QtGui.QPushButton(self.tabProgetti)
        self.prj_btCerca.setAutoDefault(False)
        self.prj_btCerca.setObjectName(_fromUtf8("prj_btCerca"))
        self.horizontalLayout_11.addWidget(self.prj_btCerca)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.prj_btApriAlbero = QtGui.QPushButton(self.tabProgetti)
        self.prj_btApriAlbero.setObjectName(_fromUtf8("prj_btApriAlbero"))
        self.horizontalLayout_13.addWidget(self.prj_btApriAlbero)
        self.prj_btChiudiAlbero = QtGui.QPushButton(self.tabProgetti)
        self.prj_btChiudiAlbero.setObjectName(_fromUtf8("prj_btChiudiAlbero"))
        self.horizontalLayout_13.addWidget(self.prj_btChiudiAlbero)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.prj_treeWidget = QtGui.QTreeWidget(self.tabProgetti)
        self.prj_treeWidget.setHeaderHidden(True)
        self.prj_treeWidget.setObjectName(_fromUtf8("prj_treeWidget"))
        self.prj_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_2.addWidget(self.prj_treeWidget)
        self.tabWidget.addTab(self.tabProgetti, _fromUtf8(""))
        self.tabPostgis = QtGui.QWidget()
        self.tabPostgis.setObjectName(_fromUtf8("tabPostgis"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabPostgis)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.tabPostgis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dati_cboCategory = QtGui.QComboBox(self.tabPostgis)
        self.dati_cboCategory.setObjectName(_fromUtf8("dati_cboCategory"))
        self.horizontalLayout_4.addWidget(self.dati_cboCategory)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.tabPostgis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dati_txFiltro = QtGui.QLineEdit(self.tabPostgis)
        self.dati_txFiltro.setObjectName(_fromUtf8("dati_txFiltro"))
        self.horizontalLayout_2.addWidget(self.dati_txFiltro)
        self.dati_btCerca = QtGui.QPushButton(self.tabPostgis)
        self.dati_btCerca.setAutoDefault(False)
        self.dati_btCerca.setObjectName(_fromUtf8("dati_btCerca"))
        self.horizontalLayout_2.addWidget(self.dati_btCerca)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dati_btApriAlbero = QtGui.QPushButton(self.tabPostgis)
        self.dati_btApriAlbero.setObjectName(_fromUtf8("dati_btApriAlbero"))
        self.horizontalLayout_3.addWidget(self.dati_btApriAlbero)
        self.dati_btChiudiAlbero = QtGui.QPushButton(self.tabPostgis)
        self.dati_btChiudiAlbero.setObjectName(_fromUtf8("dati_btChiudiAlbero"))
        self.horizontalLayout_3.addWidget(self.dati_btChiudiAlbero)
        self.dati_btMetadati = QtGui.QPushButton(self.tabPostgis)
        self.dati_btMetadati.setObjectName(_fromUtf8("dati_btMetadati"))
        self.horizontalLayout_3.addWidget(self.dati_btMetadati)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.dati_treeWidget = QtGui.QTreeWidget(self.tabPostgis)
        self.dati_treeWidget.setHeaderHidden(True)
        self.dati_treeWidget.setObjectName(_fromUtf8("dati_treeWidget"))
        self.dati_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.dati_treeWidget)
        self.groupBox = QtGui.QGroupBox(self.tabPostgis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.dati_ckLayerAbilitati = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dati_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.dati_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.dati_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.dati_ckLayerAbilitati.setChecked(False)
        self.dati_ckLayerAbilitati.setObjectName(_fromUtf8("dati_ckLayerAbilitati"))
        self.horizontalLayout_5.addWidget(self.dati_ckLayerAbilitati)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tabPostgis, _fromUtf8(""))
        self.tabRaster = QtGui.QWidget()
        self.tabRaster.setObjectName(_fromUtf8("tabRaster"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tabRaster)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout()
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_36 = QtGui.QLabel(self.tabRaster)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(50, 0))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_64.addWidget(self.label_36)
        self.raster_cboCategory = QtGui.QComboBox(self.tabRaster)
        self.raster_cboCategory.setObjectName(_fromUtf8("raster_cboCategory"))
        self.horizontalLayout_64.addWidget(self.raster_cboCategory)
        self.verticalLayout_9.addLayout(self.horizontalLayout_64)
        self.horizontalLayout_65 = QtGui.QHBoxLayout()
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_37 = QtGui.QLabel(self.tabRaster)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(50, 0))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_65.addWidget(self.label_37)
        self.raster_txFiltro = QtGui.QLineEdit(self.tabRaster)
        self.raster_txFiltro.setObjectName(_fromUtf8("raster_txFiltro"))
        self.horizontalLayout_65.addWidget(self.raster_txFiltro)
        self.raster_btCerca = QtGui.QPushButton(self.tabRaster)
        self.raster_btCerca.setAutoDefault(False)
        self.raster_btCerca.setObjectName(_fromUtf8("raster_btCerca"))
        self.horizontalLayout_65.addWidget(self.raster_btCerca)
        self.verticalLayout_9.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_66 = QtGui.QHBoxLayout()
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.raster_btApriAlbero = QtGui.QPushButton(self.tabRaster)
        self.raster_btApriAlbero.setObjectName(_fromUtf8("raster_btApriAlbero"))
        self.horizontalLayout_66.addWidget(self.raster_btApriAlbero)
        self.raster_btChiudiAlbero = QtGui.QPushButton(self.tabRaster)
        self.raster_btChiudiAlbero.setObjectName(_fromUtf8("raster_btChiudiAlbero"))
        self.horizontalLayout_66.addWidget(self.raster_btChiudiAlbero)
        self.raster_btMetadati = QtGui.QPushButton(self.tabRaster)
        self.raster_btMetadati.setObjectName(_fromUtf8("raster_btMetadati"))
        self.horizontalLayout_66.addWidget(self.raster_btMetadati)
        self.verticalLayout_9.addLayout(self.horizontalLayout_66)
        self.raster_treeWidget = QtGui.QTreeWidget(self.tabRaster)
        self.raster_treeWidget.setHeaderHidden(True)
        self.raster_treeWidget.setObjectName(_fromUtf8("raster_treeWidget"))
        self.raster_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_9.addWidget(self.raster_treeWidget)
        self.groupBox_9 = QtGui.QGroupBox(self.tabRaster)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout()
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.raster_ckLayerAbilitati = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raster_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.raster_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.raster_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.raster_ckLayerAbilitati.setChecked(False)
        self.raster_ckLayerAbilitati.setObjectName(_fromUtf8("raster_ckLayerAbilitati"))
        self.horizontalLayout_67.addWidget(self.raster_ckLayerAbilitati)
        self.verticalLayout_18.addLayout(self.horizontalLayout_67)
        self.verticalLayout_9.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tabRaster, _fromUtf8(""))
        self.tabWMS = QtGui.QWidget()
        self.tabWMS.setObjectName(_fromUtf8("tabWMS"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabWMS)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_categoria_WMS = QtGui.QHBoxLayout()
        self.horizontalLayout_categoria_WMS.setObjectName(_fromUtf8("horizontalLayout_categoria_WMS"))
        self.wms_lbCategory = QtGui.QLabel(self.tabWMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_lbCategory.sizePolicy().hasHeightForWidth())
        self.wms_lbCategory.setSizePolicy(sizePolicy)
        self.wms_lbCategory.setMinimumSize(QtCore.QSize(50, 0))
        self.wms_lbCategory.setObjectName(_fromUtf8("wms_lbCategory"))
        self.horizontalLayout_categoria_WMS.addWidget(self.wms_lbCategory)
        self.wms_cboCategory = QtGui.QComboBox(self.tabWMS)
        self.wms_cboCategory.setObjectName(_fromUtf8("wms_cboCategory"))
        self.horizontalLayout_categoria_WMS.addWidget(self.wms_cboCategory)
        self.verticalLayout_6.addLayout(self.horizontalLayout_categoria_WMS)
        self.horizontalLayout_filtro_WMS = QtGui.QHBoxLayout()
        self.horizontalLayout_filtro_WMS.setObjectName(_fromUtf8("horizontalLayout_filtro_WMS"))
        self.wms_lbFiltro = QtGui.QLabel(self.tabWMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_lbFiltro.sizePolicy().hasHeightForWidth())
        self.wms_lbFiltro.setSizePolicy(sizePolicy)
        self.wms_lbFiltro.setMinimumSize(QtCore.QSize(50, 0))
        self.wms_lbFiltro.setObjectName(_fromUtf8("wms_lbFiltro"))
        self.horizontalLayout_filtro_WMS.addWidget(self.wms_lbFiltro)
        self.wms_txFiltro = QtGui.QLineEdit(self.tabWMS)
        self.wms_txFiltro.setObjectName(_fromUtf8("wms_txFiltro"))
        self.horizontalLayout_filtro_WMS.addWidget(self.wms_txFiltro)
        self.wms_btCerca = QtGui.QPushButton(self.tabWMS)
        self.wms_btCerca.setAutoDefault(False)
        self.wms_btCerca.setObjectName(_fromUtf8("wms_btCerca"))
        self.horizontalLayout_filtro_WMS.addWidget(self.wms_btCerca)
        self.verticalLayout_6.addLayout(self.horizontalLayout_filtro_WMS)
        self.horizontalLayout_bottoni_WMS = QtGui.QHBoxLayout()
        self.horizontalLayout_bottoni_WMS.setObjectName(_fromUtf8("horizontalLayout_bottoni_WMS"))
        self.wms_btApriAlbero = QtGui.QPushButton(self.tabWMS)
        self.wms_btApriAlbero.setObjectName(_fromUtf8("wms_btApriAlbero"))
        self.horizontalLayout_bottoni_WMS.addWidget(self.wms_btApriAlbero)
        self.wms_btChiudiAlbero = QtGui.QPushButton(self.tabWMS)
        self.wms_btChiudiAlbero.setObjectName(_fromUtf8("wms_btChiudiAlbero"))
        self.horizontalLayout_bottoni_WMS.addWidget(self.wms_btChiudiAlbero)
        self.wms_btMetadati = QtGui.QPushButton(self.tabWMS)
        self.wms_btMetadati.setObjectName(_fromUtf8("wms_btMetadati"))
        self.horizontalLayout_bottoni_WMS.addWidget(self.wms_btMetadati)
        self.verticalLayout_6.addLayout(self.horizontalLayout_bottoni_WMS)
        self.wms_treeWidget = QtGui.QTreeWidget(self.tabWMS)
        self.wms_treeWidget.setHeaderHidden(True)
        self.wms_treeWidget.setObjectName(_fromUtf8("wms_treeWidget"))
        self.wms_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_6.addWidget(self.wms_treeWidget)
        self.horizontalLayout_formato_WMS = QtGui.QHBoxLayout()
        self.horizontalLayout_formato_WMS.setObjectName(_fromUtf8("horizontalLayout_formato_WMS"))
        self.wms_formatoLabel = QtGui.QLabel(self.tabWMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_formatoLabel.sizePolicy().hasHeightForWidth())
        self.wms_formatoLabel.setSizePolicy(sizePolicy)
        self.wms_formatoLabel.setObjectName(_fromUtf8("wms_formatoLabel"))
        self.horizontalLayout_formato_WMS.addWidget(self.wms_formatoLabel)
        self.wms_formatoCombo = QtGui.QComboBox(self.tabWMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_formatoCombo.sizePolicy().hasHeightForWidth())
        self.wms_formatoCombo.setSizePolicy(sizePolicy)
        self.wms_formatoCombo.setMinimumSize(QtCore.QSize(120, 0))
        self.wms_formatoCombo.setObjectName(_fromUtf8("wms_formatoCombo"))
        self.horizontalLayout_formato_WMS.addWidget(self.wms_formatoCombo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_formato_WMS.addItem(spacerItem1)
        self.wms_crsLabel = QtGui.QLabel(self.tabWMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_crsLabel.sizePolicy().hasHeightForWidth())
        self.wms_crsLabel.setSizePolicy(sizePolicy)
        self.wms_crsLabel.setObjectName(_fromUtf8("wms_crsLabel"))
        self.horizontalLayout_formato_WMS.addWidget(self.wms_crsLabel)
        self.wms_crsCombo = QtGui.QComboBox(self.tabWMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_crsCombo.sizePolicy().hasHeightForWidth())
        self.wms_crsCombo.setSizePolicy(sizePolicy)
        self.wms_crsCombo.setMinimumSize(QtCore.QSize(110, 0))
        self.wms_crsCombo.setObjectName(_fromUtf8("wms_crsCombo"))
        self.horizontalLayout_formato_WMS.addWidget(self.wms_crsCombo)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_formato_WMS.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_formato_WMS)
        self.gBox_check_WMS = QtGui.QGroupBox(self.tabWMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_check_WMS.sizePolicy().hasHeightForWidth())
        self.gBox_check_WMS.setSizePolicy(sizePolicy)
        self.gBox_check_WMS.setMinimumSize(QtCore.QSize(0, 50))
        self.gBox_check_WMS.setObjectName(_fromUtf8("gBox_check_WMS"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gBox_check_WMS)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_check_WMS = QtGui.QHBoxLayout()
        self.horizontalLayout_check_WMS.setObjectName(_fromUtf8("horizontalLayout_check_WMS"))
        self.wms_groupedCheck = QtGui.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_groupedCheck.sizePolicy().hasHeightForWidth())
        self.wms_groupedCheck.setSizePolicy(sizePolicy)
        self.wms_groupedCheck.setObjectName(_fromUtf8("wms_groupedCheck"))
        self.horizontalLayout_check_WMS.addWidget(self.wms_groupedCheck)
        self.wms_ckLayerAbilitati = QtGui.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.wms_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.wms_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.wms_ckLayerAbilitati.setChecked(False)
        self.wms_ckLayerAbilitati.setObjectName(_fromUtf8("wms_ckLayerAbilitati"))
        self.horizontalLayout_check_WMS.addWidget(self.wms_ckLayerAbilitati)
        self.wms_ckDescrizione = QtGui.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_ckDescrizione.sizePolicy().hasHeightForWidth())
        self.wms_ckDescrizione.setSizePolicy(sizePolicy)
        self.wms_ckDescrizione.setObjectName(_fromUtf8("wms_ckDescrizione"))
        self.horizontalLayout_check_WMS.addWidget(self.wms_ckDescrizione)
        self.wms_ckStampabile = QtGui.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_ckStampabile.sizePolicy().hasHeightForWidth())
        self.wms_ckStampabile.setSizePolicy(sizePolicy)
        self.wms_ckStampabile.setObjectName(_fromUtf8("wms_ckStampabile"))
        self.horizontalLayout_check_WMS.addWidget(self.wms_ckStampabile)
        self.verticalLayout_5.addLayout(self.horizontalLayout_check_WMS)
        self.verticalLayout_6.addWidget(self.gBox_check_WMS)
        self.tabWidget.addTab(self.tabWMS, _fromUtf8(""))
        self.tabIndica = QtGui.QWidget()
        self.tabIndica.setObjectName(_fromUtf8("tabIndica"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabIndica)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_categoria_Indica = QtGui.QHBoxLayout()
        self.horizontalLayout_categoria_Indica.setObjectName(_fromUtf8("horizontalLayout_categoria_Indica"))
        self.indica_lbCategory = QtGui.QLabel(self.tabIndica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbCategory.sizePolicy().hasHeightForWidth())
        self.indica_lbCategory.setSizePolicy(sizePolicy)
        self.indica_lbCategory.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbCategory.setObjectName(_fromUtf8("indica_lbCategory"))
        self.horizontalLayout_categoria_Indica.addWidget(self.indica_lbCategory)
        self.indica_cboCategory = QtGui.QComboBox(self.tabIndica)
        self.indica_cboCategory.setObjectName(_fromUtf8("indica_cboCategory"))
        self.horizontalLayout_categoria_Indica.addWidget(self.indica_cboCategory)
        self.gridLayout_4.addLayout(self.horizontalLayout_categoria_Indica, 0, 0, 1, 1)
        self.horizontalLayout_unita_Indica = QtGui.QHBoxLayout()
        self.horizontalLayout_unita_Indica.setObjectName(_fromUtf8("horizontalLayout_unita_Indica"))
        self.indica_lbUnita = QtGui.QLabel(self.tabIndica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbUnita.sizePolicy().hasHeightForWidth())
        self.indica_lbUnita.setSizePolicy(sizePolicy)
        self.indica_lbUnita.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbUnita.setObjectName(_fromUtf8("indica_lbUnita"))
        self.horizontalLayout_unita_Indica.addWidget(self.indica_lbUnita)
        self.indica_cboUnita = QtGui.QComboBox(self.tabIndica)
        self.indica_cboUnita.setObjectName(_fromUtf8("indica_cboUnita"))
        self.horizontalLayout_unita_Indica.addWidget(self.indica_cboUnita)
        self.gridLayout_4.addLayout(self.horizontalLayout_unita_Indica, 1, 0, 1, 1)
        self.horizontalLayout_periodicita_Indica = QtGui.QHBoxLayout()
        self.horizontalLayout_periodicita_Indica.setObjectName(_fromUtf8("horizontalLayout_periodicita_Indica"))
        self.indica_lbPeriodicita = QtGui.QLabel(self.tabIndica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbPeriodicita.sizePolicy().hasHeightForWidth())
        self.indica_lbPeriodicita.setSizePolicy(sizePolicy)
        self.indica_lbPeriodicita.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbPeriodicita.setObjectName(_fromUtf8("indica_lbPeriodicita"))
        self.horizontalLayout_periodicita_Indica.addWidget(self.indica_lbPeriodicita)
        self.indica_cboPeriodicita = QtGui.QComboBox(self.tabIndica)
        self.indica_cboPeriodicita.setObjectName(_fromUtf8("indica_cboPeriodicita"))
        self.horizontalLayout_periodicita_Indica.addWidget(self.indica_cboPeriodicita)
        self.gridLayout_4.addLayout(self.horizontalLayout_periodicita_Indica, 2, 0, 1, 1)
        self.horizontalLayout_filtro_Indica = QtGui.QHBoxLayout()
        self.horizontalLayout_filtro_Indica.setObjectName(_fromUtf8("horizontalLayout_filtro_Indica"))
        self.indica_lbFiltro = QtGui.QLabel(self.tabIndica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbFiltro.sizePolicy().hasHeightForWidth())
        self.indica_lbFiltro.setSizePolicy(sizePolicy)
        self.indica_lbFiltro.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbFiltro.setObjectName(_fromUtf8("indica_lbFiltro"))
        self.horizontalLayout_filtro_Indica.addWidget(self.indica_lbFiltro)
        self.indica_txFiltro = QtGui.QLineEdit(self.tabIndica)
        self.indica_txFiltro.setObjectName(_fromUtf8("indica_txFiltro"))
        self.horizontalLayout_filtro_Indica.addWidget(self.indica_txFiltro)
        self.indica_btCerca = QtGui.QPushButton(self.tabIndica)
        self.indica_btCerca.setAutoDefault(False)
        self.indica_btCerca.setObjectName(_fromUtf8("indica_btCerca"))
        self.horizontalLayout_filtro_Indica.addWidget(self.indica_btCerca)
        self.gridLayout_4.addLayout(self.horizontalLayout_filtro_Indica, 3, 0, 1, 1)
        self.horizontalLayout_bottoni_Indica = QtGui.QHBoxLayout()
        self.horizontalLayout_bottoni_Indica.setObjectName(_fromUtf8("horizontalLayout_bottoni_Indica"))
        self.indica_btApriAlbero = QtGui.QPushButton(self.tabIndica)
        self.indica_btApriAlbero.setObjectName(_fromUtf8("indica_btApriAlbero"))
        self.horizontalLayout_bottoni_Indica.addWidget(self.indica_btApriAlbero)
        self.indica_btChiudiAlbero = QtGui.QPushButton(self.tabIndica)
        self.indica_btChiudiAlbero.setObjectName(_fromUtf8("indica_btChiudiAlbero"))
        self.horizontalLayout_bottoni_Indica.addWidget(self.indica_btChiudiAlbero)
        self.indica_btMetadati = QtGui.QPushButton(self.tabIndica)
        self.indica_btMetadati.setObjectName(_fromUtf8("indica_btMetadati"))
        self.horizontalLayout_bottoni_Indica.addWidget(self.indica_btMetadati)
        self.gridLayout_4.addLayout(self.horizontalLayout_bottoni_Indica, 4, 0, 1, 1)
        self.indica_treeWidget = QtGui.QTreeWidget(self.tabIndica)
        self.indica_treeWidget.setHeaderHidden(True)
        self.indica_treeWidget.setObjectName(_fromUtf8("indica_treeWidget"))
        self.indica_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_4.addWidget(self.indica_treeWidget, 5, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_check_indica = QtGui.QGroupBox(self.tabIndica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayout_check_indica.sizePolicy().hasHeightForWidth())
        self.horizontalLayout_check_indica.setSizePolicy(sizePolicy)
        self.horizontalLayout_check_indica.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalLayout_check_indica.setObjectName(_fromUtf8("horizontalLayout_check_indica"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayout_check_indica)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.indica_ckLayerAbilitati = QtGui.QCheckBox(self.horizontalLayout_check_indica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.indica_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.indica_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.indica_ckLayerAbilitati.setChecked(False)
        self.indica_ckLayerAbilitati.setObjectName(_fromUtf8("indica_ckLayerAbilitati"))
        self.horizontalLayout.addWidget(self.indica_ckLayerAbilitati)
        self.indica_ckSerieStorica = QtGui.QCheckBox(self.horizontalLayout_check_indica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_ckSerieStorica.sizePolicy().hasHeightForWidth())
        self.indica_ckSerieStorica.setSizePolicy(sizePolicy)
        self.indica_ckSerieStorica.setObjectName(_fromUtf8("indica_ckSerieStorica"))
        self.horizontalLayout.addWidget(self.indica_ckSerieStorica)
        self.horizontalLayout_8.addWidget(self.horizontalLayout_check_indica)
        self.horizontalLayout_funzioni_indica = QtGui.QGroupBox(self.tabIndica)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayout_funzioni_indica.sizePolicy().hasHeightForWidth())
        self.horizontalLayout_funzioni_indica.setSizePolicy(sizePolicy)
        self.horizontalLayout_funzioni_indica.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalLayout_funzioni_indica.setObjectName(_fromUtf8("horizontalLayout_funzioni_indica"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayout_funzioni_indica)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.indica_btDeseleziona = QtGui.QPushButton(self.horizontalLayout_funzioni_indica)
        self.indica_btDeseleziona.setMinimumSize(QtCore.QSize(0, 25))
        self.indica_btDeseleziona.setObjectName(_fromUtf8("indica_btDeseleziona"))
        self.horizontalLayout_7.addWidget(self.indica_btDeseleziona)
        self.horizontalLayout_8.addWidget(self.horizontalLayout_funzioni_indica)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabIndica, _fromUtf8(""))
        self.tabCSW = QtGui.QWidget()
        self.tabCSW.setEnabled(True)
        self.tabCSW.setObjectName(_fromUtf8("tabCSW"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabCSW)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_13 = QtGui.QLabel(self.tabCSW)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_26.addWidget(self.label_13)
        self.csw_cboCategory = QtGui.QComboBox(self.tabCSW)
        self.csw_cboCategory.setObjectName(_fromUtf8("csw_cboCategory"))
        self.horizontalLayout_26.addWidget(self.csw_cboCategory)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_14 = QtGui.QLabel(self.tabCSW)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(50, 0))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_25.addWidget(self.label_14)
        self.csw_txFiltro = QtGui.QLineEdit(self.tabCSW)
        self.csw_txFiltro.setObjectName(_fromUtf8("csw_txFiltro"))
        self.horizontalLayout_25.addWidget(self.csw_txFiltro)
        self.csw_btCerca = QtGui.QPushButton(self.tabCSW)
        self.csw_btCerca.setAutoDefault(False)
        self.csw_btCerca.setObjectName(_fromUtf8("csw_btCerca"))
        self.horizontalLayout_25.addWidget(self.csw_btCerca)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.csw_btApriAlbero = QtGui.QPushButton(self.tabCSW)
        self.csw_btApriAlbero.setObjectName(_fromUtf8("csw_btApriAlbero"))
        self.horizontalLayout_24.addWidget(self.csw_btApriAlbero)
        self.csw_btChiudiAlbero = QtGui.QPushButton(self.tabCSW)
        self.csw_btChiudiAlbero.setObjectName(_fromUtf8("csw_btChiudiAlbero"))
        self.horizontalLayout_24.addWidget(self.csw_btChiudiAlbero)
        self.csw_btMetadati = QtGui.QPushButton(self.tabCSW)
        self.csw_btMetadati.setObjectName(_fromUtf8("csw_btMetadati"))
        self.horizontalLayout_24.addWidget(self.csw_btMetadati)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.csw_treeWidget = QtGui.QTreeWidget(self.tabCSW)
        self.csw_treeWidget.setHeaderHidden(True)
        self.csw_treeWidget.setObjectName(_fromUtf8("csw_treeWidget"))
        self.csw_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_10.addWidget(self.csw_treeWidget)
        self.groupBox_3 = QtGui.QGroupBox(self.tabCSW)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.csw_groupedCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csw_groupedCheck.sizePolicy().hasHeightForWidth())
        self.csw_groupedCheck.setSizePolicy(sizePolicy)
        self.csw_groupedCheck.setObjectName(_fromUtf8("csw_groupedCheck"))
        self.horizontalLayout_16.addWidget(self.csw_groupedCheck)
        self.csw_ckLayerAbilitati = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csw_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.csw_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.csw_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.csw_ckLayerAbilitati.setChecked(False)
        self.csw_ckLayerAbilitati.setObjectName(_fromUtf8("csw_ckLayerAbilitati"))
        self.horizontalLayout_16.addWidget(self.csw_ckLayerAbilitati)
        self.csw_ckDescrizione = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csw_ckDescrizione.sizePolicy().hasHeightForWidth())
        self.csw_ckDescrizione.setSizePolicy(sizePolicy)
        self.csw_ckDescrizione.setObjectName(_fromUtf8("csw_ckDescrizione"))
        self.horizontalLayout_16.addWidget(self.csw_ckDescrizione)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tabCSW, _fromUtf8(""))
        self.tabConf = QtGui.QWidget()
        self.tabConf.setObjectName(_fromUtf8("tabConf"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabConf)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 9, 415, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.conf_chkLocale = QtGui.QCheckBox(self.groupBox_4)
        self.conf_chkLocale.setGeometry(QtCore.QRect(30, 20, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_chkLocale.sizePolicy().hasHeightForWidth())
        self.conf_chkLocale.setSizePolicy(sizePolicy)
        self.conf_chkLocale.setObjectName(_fromUtf8("conf_chkLocale"))
        self.conf_btnAbout = QtGui.QPushButton(self.groupBox_4)
        self.conf_btnAbout.setGeometry(QtCore.QRect(280, 0, 92, 48))
        self.conf_btnAbout.setMinimumSize(QtCore.QSize(80, 40))
        self.conf_btnAbout.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/csiatlante/icons/logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conf_btnAbout.setIcon(icon)
        self.conf_btnAbout.setIconSize(QtCore.QSize(80, 40))
        self.conf_btnAbout.setObjectName(_fromUtf8("conf_btnAbout"))
        self.groupBoxServiceConnections = QtGui.QGroupBox(self.tabConf)
        self.groupBoxServiceConnections.setGeometry(QtCore.QRect(9, 55, 415, 116))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxServiceConnections.sizePolicy().hasHeightForWidth())
        self.groupBoxServiceConnections.setSizePolicy(sizePolicy)
        self.groupBoxServiceConnections.setObjectName(_fromUtf8("groupBoxServiceConnections"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxServiceConnections)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.label_15 = QtGui.QLabel(self.groupBoxServiceConnections)
        self.label_15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_20.addWidget(self.label_15)
        self.conf_cboServiceConnections = QtGui.QComboBox(self.groupBoxServiceConnections)
        self.conf_cboServiceConnections.setMaximumSize(QtCore.QSize(300, 20))
        self.conf_cboServiceConnections.setObjectName(_fromUtf8("conf_cboServiceConnections"))
        self.horizontalLayout_20.addWidget(self.conf_cboServiceConnections)
        self.gridLayout.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.conf_btnServiceNew = QtGui.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceNew.setObjectName(_fromUtf8("conf_btnServiceNew"))
        self.horizontalLayout_18.addWidget(self.conf_btnServiceNew)
        self.conf_btnServiceEdit = QtGui.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceEdit.setObjectName(_fromUtf8("conf_btnServiceEdit"))
        self.horizontalLayout_18.addWidget(self.conf_btnServiceEdit)
        self.conf_btnServiceDelete = QtGui.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceDelete.setObjectName(_fromUtf8("conf_btnServiceDelete"))
        self.horizontalLayout_18.addWidget(self.conf_btnServiceDelete)
        self.gridLayout.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.conf_btnServiceSaveFile = QtGui.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceSaveFile.setObjectName(_fromUtf8("conf_btnServiceSaveFile"))
        self.horizontalLayout_19.addWidget(self.conf_btnServiceSaveFile)
        self.conf_btnServiceLoadFile = QtGui.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceLoadFile.setObjectName(_fromUtf8("conf_btnServiceLoadFile"))
        self.horizontalLayout_19.addWidget(self.conf_btnServiceLoadFile)
        self.conf_btnServiceLoadDefault = QtGui.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceLoadDefault.setEnabled(False)
        self.conf_btnServiceLoadDefault.setObjectName(_fromUtf8("conf_btnServiceLoadDefault"))
        self.horizontalLayout_19.addWidget(self.conf_btnServiceLoadDefault)
        self.gridLayout.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.groupBoxConnections = QtGui.QGroupBox(self.tabConf)
        self.groupBoxConnections.setGeometry(QtCore.QRect(9, 177, 411, 117))
        self.groupBoxConnections.setObjectName(_fromUtf8("groupBoxConnections"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxConnections)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_17 = QtGui.QLabel(self.groupBoxConnections)
        self.label_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_22.addWidget(self.label_17)
        self.conf_cboConnections = QtGui.QComboBox(self.groupBoxConnections)
        self.conf_cboConnections.setMaximumSize(QtCore.QSize(300, 20))
        self.conf_cboConnections.setObjectName(_fromUtf8("conf_cboConnections"))
        self.horizontalLayout_22.addWidget(self.conf_cboConnections)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.conf_btnNew = QtGui.QPushButton(self.groupBoxConnections)
        self.conf_btnNew.setObjectName(_fromUtf8("conf_btnNew"))
        self.horizontalLayout_27.addWidget(self.conf_btnNew)
        self.conf_btnEdit = QtGui.QPushButton(self.groupBoxConnections)
        self.conf_btnEdit.setObjectName(_fromUtf8("conf_btnEdit"))
        self.horizontalLayout_27.addWidget(self.conf_btnEdit)
        self.conf_btnDelete = QtGui.QPushButton(self.groupBoxConnections)
        self.conf_btnDelete.setObjectName(_fromUtf8("conf_btnDelete"))
        self.horizontalLayout_27.addWidget(self.conf_btnDelete)
        self.gridLayout_2.addLayout(self.horizontalLayout_27, 1, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.conf_btnSaveFile = QtGui.QPushButton(self.groupBoxConnections)
        self.conf_btnSaveFile.setObjectName(_fromUtf8("conf_btnSaveFile"))
        self.horizontalLayout_28.addWidget(self.conf_btnSaveFile)
        self.conf_btnLoadFile = QtGui.QPushButton(self.groupBoxConnections)
        self.conf_btnLoadFile.setObjectName(_fromUtf8("conf_btnLoadFile"))
        self.horizontalLayout_28.addWidget(self.conf_btnLoadFile)
        self.conf_btnLoadDefault = QtGui.QPushButton(self.groupBoxConnections)
        self.conf_btnLoadDefault.setEnabled(False)
        self.conf_btnLoadDefault.setObjectName(_fromUtf8("conf_btnLoadDefault"))
        self.horizontalLayout_28.addWidget(self.conf_btnLoadDefault)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabConf, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btAggiorna = QtGui.QPushButton(self.dockWidgetContents)
        self.btAggiorna.setObjectName(_fromUtf8("btAggiorna"))
        self.horizontalLayout_6.addWidget(self.btAggiorna)
        self.btCarica = QtGui.QPushButton(self.dockWidgetContents)
        self.btCarica.setObjectName(_fromUtf8("btCarica"))
        self.horizontalLayout_6.addWidget(self.btCarica)
        self.btSvuotaToc = QtGui.QPushButton(self.dockWidgetContents)
        self.btSvuotaToc.setObjectName(_fromUtf8("btSvuotaToc"))
        self.horizontalLayout_6.addWidget(self.btSvuotaToc)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        CsiAtlante.setWidget(self.dockWidgetContents)

        self.retranslateUi(CsiAtlante)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(CsiAtlante)

    def retranslateUi(self, CsiAtlante):
        CsiAtlante.setWindowTitle(_translate("CsiAtlante", "CSI Atlante", None))
        self.label_10.setText(_translate("CsiAtlante", "Categoria", None))
        self.label_9.setText(_translate("CsiAtlante", "Filtro", None))
        self.prj_btCerca.setText(_translate("CsiAtlante", "Cerca", None))
        self.prj_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto", None))
        self.prj_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProgetti), _translate("CsiAtlante", "Progetti", None))
        self.label_4.setText(_translate("CsiAtlante", "Categoria", None))
        self.label_3.setText(_translate("CsiAtlante", "Filtro", None))
        self.dati_btCerca.setText(_translate("CsiAtlante", "Cerca", None))
        self.dati_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto", None))
        self.dati_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto", None))
        self.dati_btMetadati.setText(_translate("CsiAtlante", "Metadati", None))
        self.groupBox.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC", None))
        self.dati_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (più lento)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPostgis), _translate("CsiAtlante", "Vector", None))
        self.label_36.setText(_translate("CsiAtlante", "Categoria", None))
        self.label_37.setText(_translate("CsiAtlante", "Filtro", None))
        self.raster_btCerca.setText(_translate("CsiAtlante", "Cerca", None))
        self.raster_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto", None))
        self.raster_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto", None))
        self.raster_btMetadati.setText(_translate("CsiAtlante", "Metadati", None))
        self.groupBox_9.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC", None))
        self.raster_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (più lento)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRaster), _translate("CsiAtlante", "Raster", None))
        self.wms_lbCategory.setText(_translate("CsiAtlante", "Categoria", None))
        self.wms_lbFiltro.setText(_translate("CsiAtlante", "Filtro", None))
        self.wms_btCerca.setText(_translate("CsiAtlante", "Cerca", None))
        self.wms_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto", None))
        self.wms_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto", None))
        self.wms_btMetadati.setText(_translate("CsiAtlante", "Metadati", None))
        self.wms_formatoLabel.setText(_translate("CsiAtlante", "Formato", None))
        self.wms_crsLabel.setText(_translate("CsiAtlante", "CRS", None))
        self.gBox_check_WMS.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC", None))
        self.wms_groupedCheck.setText(_translate("CsiAtlante", "Separati in gruppo", None))
        self.wms_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (+ lento)", None))
        self.wms_ckDescrizione.setText(_translate("CsiAtlante", "Breve", None))
        self.wms_ckStampabile.setText(_translate("CsiAtlante", "Stampabile", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWMS), _translate("CsiAtlante", "Geoservizi", None))
        self.indica_lbCategory.setText(_translate("CsiAtlante", "Categoria", None))
        self.indica_lbUnita.setText(_translate("CsiAtlante", "Unità territoriale", None))
        self.indica_lbPeriodicita.setText(_translate("CsiAtlante", "Periodicità", None))
        self.indica_lbFiltro.setText(_translate("CsiAtlante", "Filtro", None))
        self.indica_btCerca.setText(_translate("CsiAtlante", "Cerca", None))
        self.indica_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto", None))
        self.indica_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto", None))
        self.indica_btMetadati.setText(_translate("CsiAtlante", "Metadati", None))
        self.horizontalLayout_check_indica.setTitle(_translate("CsiAtlante", "Gestione visualizzazione indicatori", None))
        self.indica_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (+ lento)", None))
        self.indica_ckSerieStorica.setText(_translate("CsiAtlante", "Serie Storica", None))
        self.horizontalLayout_funzioni_indica.setTitle(_translate("CsiAtlante", "Funzioni Indicatori", None))
        self.indica_btDeseleziona.setText(_translate("CsiAtlante", "Deseleziona Nodi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIndica), _translate("CsiAtlante", "Indicatori", None))
        self.label_13.setText(_translate("CsiAtlante", "Server", None))
        self.label_14.setText(_translate("CsiAtlante", "Filtro", None))
        self.csw_btCerca.setText(_translate("CsiAtlante", "Cerca", None))
        self.csw_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto", None))
        self.csw_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto", None))
        self.csw_btMetadati.setText(_translate("CsiAtlante", "Metadati", None))
        self.groupBox_3.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC", None))
        self.csw_groupedCheck.setText(_translate("CsiAtlante", "Separati in un gruppo", None))
        self.csw_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (più lento)", None))
        self.csw_ckDescrizione.setText(_translate("CsiAtlante", "Descrizione breve", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCSW), _translate("CsiAtlante", "CSW", None))
        self.groupBox_4.setTitle(_translate("CsiAtlante", "Comportamento", None))
        self.conf_chkLocale.setText(_translate("CsiAtlante", "Fuori Linea (file locali)", None))
        self.groupBoxServiceConnections.setTitle(_translate("CsiAtlante", "Connessioni Servizi", None))
        self.label_15.setText(_translate("CsiAtlante", "<html><head/><body><p><span style=\" font-weight:600;\">In uso :</span></p></body></html>", None))
        self.conf_btnServiceNew.setText(_translate("CsiAtlante", "Nuova", None))
        self.conf_btnServiceEdit.setText(_translate("CsiAtlante", "Modifica", None))
        self.conf_btnServiceDelete.setText(_translate("CsiAtlante", "Elimina", None))
        self.conf_btnServiceSaveFile.setText(_translate("CsiAtlante", "Salva su file", None))
        self.conf_btnServiceLoadFile.setText(_translate("CsiAtlante", "Carica da file", None))
        self.conf_btnServiceLoadDefault.setText(_translate("CsiAtlante", "Carica Default", None))
        self.groupBoxConnections.setTitle(_translate("CsiAtlante", "Portafoglio Connessioni DB", None))
        self.label_17.setText(_translate("CsiAtlante", "Lista:", None))
        self.conf_btnNew.setText(_translate("CsiAtlante", "Nuova", None))
        self.conf_btnEdit.setText(_translate("CsiAtlante", "Modifica", None))
        self.conf_btnDelete.setText(_translate("CsiAtlante", "Elimina", None))
        self.conf_btnSaveFile.setText(_translate("CsiAtlante", "Salva su file", None))
        self.conf_btnLoadFile.setText(_translate("CsiAtlante", "Carica da file", None))
        self.conf_btnLoadDefault.setText(_translate("CsiAtlante", "Carica Default", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConf), _translate("CsiAtlante", "Impostazioni", None))
        self.btAggiorna.setText(_translate("CsiAtlante", "Aggiorna Cache", None))
        self.btCarica.setText(_translate("CsiAtlante", "Carica", None))
        self.btSvuotaToc.setText(_translate("CsiAtlante", "Ripulisci Dati TOC", None))

import resources_rc
