# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_csiatlante.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CsiAtlante(object):
    def setupUi(self, CsiAtlante):
        CsiAtlante.setObjectName("CsiAtlante")
        CsiAtlante.resize(461, 458)
        CsiAtlante.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(0, 436))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabProgetti = QtWidgets.QWidget()
        self.tabProgetti.setObjectName("tabProgetti")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabProgetti)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.tabProgetti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.prj_cboCategory = QtWidgets.QComboBox(self.tabProgetti)
        self.prj_cboCategory.setObjectName("prj_cboCategory")
        self.horizontalLayout_12.addWidget(self.prj_cboCategory)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.tabProgetti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.prj_txFiltro = QtWidgets.QLineEdit(self.tabProgetti)
        self.prj_txFiltro.setObjectName("prj_txFiltro")
        self.horizontalLayout_11.addWidget(self.prj_txFiltro)
        self.prj_btCerca = QtWidgets.QPushButton(self.tabProgetti)
        self.prj_btCerca.setAutoDefault(False)
        self.prj_btCerca.setObjectName("prj_btCerca")
        self.horizontalLayout_11.addWidget(self.prj_btCerca)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.prj_btApriAlbero = QtWidgets.QPushButton(self.tabProgetti)
        self.prj_btApriAlbero.setObjectName("prj_btApriAlbero")
        self.horizontalLayout_13.addWidget(self.prj_btApriAlbero)
        self.prj_btChiudiAlbero = QtWidgets.QPushButton(self.tabProgetti)
        self.prj_btChiudiAlbero.setObjectName("prj_btChiudiAlbero")
        self.horizontalLayout_13.addWidget(self.prj_btChiudiAlbero)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.prj_treeWidget = QtWidgets.QTreeWidget(self.tabProgetti)
        self.prj_treeWidget.setHeaderHidden(True)
        self.prj_treeWidget.setObjectName("prj_treeWidget")
        self.prj_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.prj_treeWidget)
        self.tabWidget.addTab(self.tabProgetti, "")
        self.tabPostgis = QtWidgets.QWidget()
        self.tabPostgis.setObjectName("tabPostgis")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabPostgis)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tabPostgis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dati_cboCategory = QtWidgets.QComboBox(self.tabPostgis)
        self.dati_cboCategory.setObjectName("dati_cboCategory")
        self.horizontalLayout_4.addWidget(self.dati_cboCategory)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tabPostgis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dati_txFiltro = QtWidgets.QLineEdit(self.tabPostgis)
        self.dati_txFiltro.setObjectName("dati_txFiltro")
        self.horizontalLayout_2.addWidget(self.dati_txFiltro)
        self.dati_btCerca = QtWidgets.QPushButton(self.tabPostgis)
        self.dati_btCerca.setAutoDefault(False)
        self.dati_btCerca.setObjectName("dati_btCerca")
        self.horizontalLayout_2.addWidget(self.dati_btCerca)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dati_btApriAlbero = QtWidgets.QPushButton(self.tabPostgis)
        self.dati_btApriAlbero.setObjectName("dati_btApriAlbero")
        self.horizontalLayout_3.addWidget(self.dati_btApriAlbero)
        self.dati_btChiudiAlbero = QtWidgets.QPushButton(self.tabPostgis)
        self.dati_btChiudiAlbero.setObjectName("dati_btChiudiAlbero")
        self.horizontalLayout_3.addWidget(self.dati_btChiudiAlbero)
        self.dati_btMetadati = QtWidgets.QPushButton(self.tabPostgis)
        self.dati_btMetadati.setObjectName("dati_btMetadati")
        self.horizontalLayout_3.addWidget(self.dati_btMetadati)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.dati_treeWidget = QtWidgets.QTreeWidget(self.tabPostgis)
        self.dati_treeWidget.setHeaderHidden(True)
        self.dati_treeWidget.setObjectName("dati_treeWidget")
        self.dati_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.dati_treeWidget)
        self.groupBox = QtWidgets.QGroupBox(self.tabPostgis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dati_ckLayerAbilitati = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dati_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.dati_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.dati_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.dati_ckLayerAbilitati.setChecked(False)
        self.dati_ckLayerAbilitati.setObjectName("dati_ckLayerAbilitati")
        self.horizontalLayout_5.addWidget(self.dati_ckLayerAbilitati)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tabPostgis, "")
        self.tabRaster = QtWidgets.QWidget()
        self.tabRaster.setObjectName("tabRaster")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabRaster)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.label_36 = QtWidgets.QLabel(self.tabRaster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(50, 0))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_64.addWidget(self.label_36)
        self.raster_cboCategory = QtWidgets.QComboBox(self.tabRaster)
        self.raster_cboCategory.setObjectName("raster_cboCategory")
        self.horizontalLayout_64.addWidget(self.raster_cboCategory)
        self.verticalLayout_9.addLayout(self.horizontalLayout_64)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.label_37 = QtWidgets.QLabel(self.tabRaster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(50, 0))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_65.addWidget(self.label_37)
        self.raster_txFiltro = QtWidgets.QLineEdit(self.tabRaster)
        self.raster_txFiltro.setObjectName("raster_txFiltro")
        self.horizontalLayout_65.addWidget(self.raster_txFiltro)
        self.raster_btCerca = QtWidgets.QPushButton(self.tabRaster)
        self.raster_btCerca.setAutoDefault(False)
        self.raster_btCerca.setObjectName("raster_btCerca")
        self.horizontalLayout_65.addWidget(self.raster_btCerca)
        self.verticalLayout_9.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.raster_btApriAlbero = QtWidgets.QPushButton(self.tabRaster)
        self.raster_btApriAlbero.setObjectName("raster_btApriAlbero")
        self.horizontalLayout_66.addWidget(self.raster_btApriAlbero)
        self.raster_btChiudiAlbero = QtWidgets.QPushButton(self.tabRaster)
        self.raster_btChiudiAlbero.setObjectName("raster_btChiudiAlbero")
        self.horizontalLayout_66.addWidget(self.raster_btChiudiAlbero)
        self.raster_btMetadati = QtWidgets.QPushButton(self.tabRaster)
        self.raster_btMetadati.setObjectName("raster_btMetadati")
        self.horizontalLayout_66.addWidget(self.raster_btMetadati)
        self.verticalLayout_9.addLayout(self.horizontalLayout_66)
        self.raster_treeWidget = QtWidgets.QTreeWidget(self.tabRaster)
        self.raster_treeWidget.setHeaderHidden(True)
        self.raster_treeWidget.setObjectName("raster_treeWidget")
        self.raster_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_9.addWidget(self.raster_treeWidget)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tabRaster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.raster_ckLayerAbilitati = QtWidgets.QCheckBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raster_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.raster_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.raster_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.raster_ckLayerAbilitati.setChecked(False)
        self.raster_ckLayerAbilitati.setObjectName("raster_ckLayerAbilitati")
        self.horizontalLayout_67.addWidget(self.raster_ckLayerAbilitati)
        self.verticalLayout_18.addLayout(self.horizontalLayout_67)
        self.verticalLayout_9.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tabRaster, "")
        self.tabWMS = QtWidgets.QWidget()
        self.tabWMS.setObjectName("tabWMS")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabWMS)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_categoria_WMS = QtWidgets.QHBoxLayout()
        self.horizontalLayout_categoria_WMS.setObjectName("horizontalLayout_categoria_WMS")
        self.wms_lbCategory = QtWidgets.QLabel(self.tabWMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_lbCategory.sizePolicy().hasHeightForWidth())
        self.wms_lbCategory.setSizePolicy(sizePolicy)
        self.wms_lbCategory.setMinimumSize(QtCore.QSize(50, 0))
        self.wms_lbCategory.setObjectName("wms_lbCategory")
        self.horizontalLayout_categoria_WMS.addWidget(self.wms_lbCategory)
        self.wms_cboCategory = QtWidgets.QComboBox(self.tabWMS)
        self.wms_cboCategory.setObjectName("wms_cboCategory")
        self.horizontalLayout_categoria_WMS.addWidget(self.wms_cboCategory)
        self.verticalLayout_6.addLayout(self.horizontalLayout_categoria_WMS)
        self.horizontalLayout_filtro_WMS = QtWidgets.QHBoxLayout()
        self.horizontalLayout_filtro_WMS.setObjectName("horizontalLayout_filtro_WMS")
        self.wms_lbFiltro = QtWidgets.QLabel(self.tabWMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_lbFiltro.sizePolicy().hasHeightForWidth())
        self.wms_lbFiltro.setSizePolicy(sizePolicy)
        self.wms_lbFiltro.setMinimumSize(QtCore.QSize(50, 0))
        self.wms_lbFiltro.setObjectName("wms_lbFiltro")
        self.horizontalLayout_filtro_WMS.addWidget(self.wms_lbFiltro)
        self.wms_txFiltro = QtWidgets.QLineEdit(self.tabWMS)
        self.wms_txFiltro.setObjectName("wms_txFiltro")
        self.horizontalLayout_filtro_WMS.addWidget(self.wms_txFiltro)
        self.wms_btCerca = QtWidgets.QPushButton(self.tabWMS)
        self.wms_btCerca.setAutoDefault(False)
        self.wms_btCerca.setObjectName("wms_btCerca")
        self.horizontalLayout_filtro_WMS.addWidget(self.wms_btCerca)
        self.verticalLayout_6.addLayout(self.horizontalLayout_filtro_WMS)
        self.horizontalLayout_bottoni_WMS = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bottoni_WMS.setObjectName("horizontalLayout_bottoni_WMS")
        self.wms_btApriAlbero = QtWidgets.QPushButton(self.tabWMS)
        self.wms_btApriAlbero.setObjectName("wms_btApriAlbero")
        self.horizontalLayout_bottoni_WMS.addWidget(self.wms_btApriAlbero)
        self.wms_btChiudiAlbero = QtWidgets.QPushButton(self.tabWMS)
        self.wms_btChiudiAlbero.setObjectName("wms_btChiudiAlbero")
        self.horizontalLayout_bottoni_WMS.addWidget(self.wms_btChiudiAlbero)
        self.wms_btMetadati = QtWidgets.QPushButton(self.tabWMS)
        self.wms_btMetadati.setObjectName("wms_btMetadati")
        self.horizontalLayout_bottoni_WMS.addWidget(self.wms_btMetadati)
        self.verticalLayout_6.addLayout(self.horizontalLayout_bottoni_WMS)
        self.wms_treeWidget = QtWidgets.QTreeWidget(self.tabWMS)
        self.wms_treeWidget.setHeaderHidden(True)
        self.wms_treeWidget.setObjectName("wms_treeWidget")
        self.wms_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_6.addWidget(self.wms_treeWidget)
        self.horizontalLayout_formato_WMS = QtWidgets.QHBoxLayout()
        self.horizontalLayout_formato_WMS.setObjectName("horizontalLayout_formato_WMS")
        self.wms_formatoLabel = QtWidgets.QLabel(self.tabWMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_formatoLabel.sizePolicy().hasHeightForWidth())
        self.wms_formatoLabel.setSizePolicy(sizePolicy)
        self.wms_formatoLabel.setObjectName("wms_formatoLabel")
        self.horizontalLayout_formato_WMS.addWidget(self.wms_formatoLabel)
        self.wms_formatoCombo = QtWidgets.QComboBox(self.tabWMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_formatoCombo.sizePolicy().hasHeightForWidth())
        self.wms_formatoCombo.setSizePolicy(sizePolicy)
        self.wms_formatoCombo.setMinimumSize(QtCore.QSize(120, 0))
        self.wms_formatoCombo.setObjectName("wms_formatoCombo")
        self.horizontalLayout_formato_WMS.addWidget(self.wms_formatoCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_formato_WMS.addItem(spacerItem1)
        self.wms_crsLabel = QtWidgets.QLabel(self.tabWMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_crsLabel.sizePolicy().hasHeightForWidth())
        self.wms_crsLabel.setSizePolicy(sizePolicy)
        self.wms_crsLabel.setObjectName("wms_crsLabel")
        self.horizontalLayout_formato_WMS.addWidget(self.wms_crsLabel)
        self.wms_crsCombo = QtWidgets.QComboBox(self.tabWMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_crsCombo.sizePolicy().hasHeightForWidth())
        self.wms_crsCombo.setSizePolicy(sizePolicy)
        self.wms_crsCombo.setMinimumSize(QtCore.QSize(110, 0))
        self.wms_crsCombo.setObjectName("wms_crsCombo")
        self.horizontalLayout_formato_WMS.addWidget(self.wms_crsCombo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_formato_WMS.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_formato_WMS)
        self.gBox_check_WMS = QtWidgets.QGroupBox(self.tabWMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_check_WMS.sizePolicy().hasHeightForWidth())
        self.gBox_check_WMS.setSizePolicy(sizePolicy)
        self.gBox_check_WMS.setMinimumSize(QtCore.QSize(0, 50))
        self.gBox_check_WMS.setObjectName("gBox_check_WMS")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gBox_check_WMS)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_check_WMS = QtWidgets.QHBoxLayout()
        self.horizontalLayout_check_WMS.setObjectName("horizontalLayout_check_WMS")
        self.wms_groupedCheck = QtWidgets.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_groupedCheck.sizePolicy().hasHeightForWidth())
        self.wms_groupedCheck.setSizePolicy(sizePolicy)
        self.wms_groupedCheck.setObjectName("wms_groupedCheck")
        self.horizontalLayout_check_WMS.addWidget(self.wms_groupedCheck)
        self.wms_ckLayerAbilitati = QtWidgets.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.wms_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.wms_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.wms_ckLayerAbilitati.setChecked(False)
        self.wms_ckLayerAbilitati.setObjectName("wms_ckLayerAbilitati")
        self.horizontalLayout_check_WMS.addWidget(self.wms_ckLayerAbilitati)
        self.wms_ckDescrizione = QtWidgets.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_ckDescrizione.sizePolicy().hasHeightForWidth())
        self.wms_ckDescrizione.setSizePolicy(sizePolicy)
        self.wms_ckDescrizione.setObjectName("wms_ckDescrizione")
        self.horizontalLayout_check_WMS.addWidget(self.wms_ckDescrizione)
        self.wms_ckStampabile = QtWidgets.QCheckBox(self.gBox_check_WMS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wms_ckStampabile.sizePolicy().hasHeightForWidth())
        self.wms_ckStampabile.setSizePolicy(sizePolicy)
        self.wms_ckStampabile.setObjectName("wms_ckStampabile")
        self.horizontalLayout_check_WMS.addWidget(self.wms_ckStampabile)
        self.verticalLayout_5.addLayout(self.horizontalLayout_check_WMS)
        self.verticalLayout_6.addWidget(self.gBox_check_WMS)
        self.tabWidget.addTab(self.tabWMS, "")
        self.tabIndica = QtWidgets.QWidget()
        self.tabIndica.setObjectName("tabIndica")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabIndica)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_categoria_Indica = QtWidgets.QHBoxLayout()
        self.horizontalLayout_categoria_Indica.setObjectName("horizontalLayout_categoria_Indica")
        self.indica_lbCategory = QtWidgets.QLabel(self.tabIndica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbCategory.sizePolicy().hasHeightForWidth())
        self.indica_lbCategory.setSizePolicy(sizePolicy)
        self.indica_lbCategory.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbCategory.setObjectName("indica_lbCategory")
        self.horizontalLayout_categoria_Indica.addWidget(self.indica_lbCategory)
        self.indica_cboCategory = QtWidgets.QComboBox(self.tabIndica)
        self.indica_cboCategory.setObjectName("indica_cboCategory")
        self.horizontalLayout_categoria_Indica.addWidget(self.indica_cboCategory)
        self.gridLayout_4.addLayout(self.horizontalLayout_categoria_Indica, 0, 0, 1, 1)
        self.horizontalLayout_unita_Indica = QtWidgets.QHBoxLayout()
        self.horizontalLayout_unita_Indica.setObjectName("horizontalLayout_unita_Indica")
        self.indica_lbUnita = QtWidgets.QLabel(self.tabIndica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbUnita.sizePolicy().hasHeightForWidth())
        self.indica_lbUnita.setSizePolicy(sizePolicy)
        self.indica_lbUnita.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbUnita.setObjectName("indica_lbUnita")
        self.horizontalLayout_unita_Indica.addWidget(self.indica_lbUnita)
        self.indica_cboUnita = QtWidgets.QComboBox(self.tabIndica)
        self.indica_cboUnita.setObjectName("indica_cboUnita")
        self.horizontalLayout_unita_Indica.addWidget(self.indica_cboUnita)
        self.gridLayout_4.addLayout(self.horizontalLayout_unita_Indica, 1, 0, 1, 1)
        self.horizontalLayout_periodicita_Indica = QtWidgets.QHBoxLayout()
        self.horizontalLayout_periodicita_Indica.setObjectName("horizontalLayout_periodicita_Indica")
        self.indica_lbPeriodicita = QtWidgets.QLabel(self.tabIndica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbPeriodicita.sizePolicy().hasHeightForWidth())
        self.indica_lbPeriodicita.setSizePolicy(sizePolicy)
        self.indica_lbPeriodicita.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbPeriodicita.setObjectName("indica_lbPeriodicita")
        self.horizontalLayout_periodicita_Indica.addWidget(self.indica_lbPeriodicita)
        self.indica_cboPeriodicita = QtWidgets.QComboBox(self.tabIndica)
        self.indica_cboPeriodicita.setObjectName("indica_cboPeriodicita")
        self.horizontalLayout_periodicita_Indica.addWidget(self.indica_cboPeriodicita)
        self.gridLayout_4.addLayout(self.horizontalLayout_periodicita_Indica, 2, 0, 1, 1)
        self.horizontalLayout_filtro_Indica = QtWidgets.QHBoxLayout()
        self.horizontalLayout_filtro_Indica.setObjectName("horizontalLayout_filtro_Indica")
        self.indica_lbFiltro = QtWidgets.QLabel(self.tabIndica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_lbFiltro.sizePolicy().hasHeightForWidth())
        self.indica_lbFiltro.setSizePolicy(sizePolicy)
        self.indica_lbFiltro.setMinimumSize(QtCore.QSize(50, 0))
        self.indica_lbFiltro.setObjectName("indica_lbFiltro")
        self.horizontalLayout_filtro_Indica.addWidget(self.indica_lbFiltro)
        self.indica_txFiltro = QtWidgets.QLineEdit(self.tabIndica)
        self.indica_txFiltro.setObjectName("indica_txFiltro")
        self.horizontalLayout_filtro_Indica.addWidget(self.indica_txFiltro)
        self.indica_btCerca = QtWidgets.QPushButton(self.tabIndica)
        self.indica_btCerca.setAutoDefault(False)
        self.indica_btCerca.setObjectName("indica_btCerca")
        self.horizontalLayout_filtro_Indica.addWidget(self.indica_btCerca)
        self.gridLayout_4.addLayout(self.horizontalLayout_filtro_Indica, 3, 0, 1, 1)
        self.horizontalLayout_bottoni_Indica = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bottoni_Indica.setObjectName("horizontalLayout_bottoni_Indica")
        self.indica_btApriAlbero = QtWidgets.QPushButton(self.tabIndica)
        self.indica_btApriAlbero.setObjectName("indica_btApriAlbero")
        self.horizontalLayout_bottoni_Indica.addWidget(self.indica_btApriAlbero)
        self.indica_btChiudiAlbero = QtWidgets.QPushButton(self.tabIndica)
        self.indica_btChiudiAlbero.setObjectName("indica_btChiudiAlbero")
        self.horizontalLayout_bottoni_Indica.addWidget(self.indica_btChiudiAlbero)
        self.indica_btMetadati = QtWidgets.QPushButton(self.tabIndica)
        self.indica_btMetadati.setObjectName("indica_btMetadati")
        self.horizontalLayout_bottoni_Indica.addWidget(self.indica_btMetadati)
        self.gridLayout_4.addLayout(self.horizontalLayout_bottoni_Indica, 4, 0, 1, 1)
        self.indica_treeWidget = QtWidgets.QTreeWidget(self.tabIndica)
        self.indica_treeWidget.setHeaderHidden(True)
        self.indica_treeWidget.setObjectName("indica_treeWidget")
        self.indica_treeWidget.headerItem().setText(0, "1")
        self.gridLayout_4.addWidget(self.indica_treeWidget, 5, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_check_indica = QtWidgets.QGroupBox(self.tabIndica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayout_check_indica.sizePolicy().hasHeightForWidth())
        self.horizontalLayout_check_indica.setSizePolicy(sizePolicy)
        self.horizontalLayout_check_indica.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalLayout_check_indica.setObjectName("horizontalLayout_check_indica")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayout_check_indica)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.indica_ckLayerAbilitati = QtWidgets.QCheckBox(self.horizontalLayout_check_indica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.indica_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.indica_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.indica_ckLayerAbilitati.setChecked(False)
        self.indica_ckLayerAbilitati.setObjectName("indica_ckLayerAbilitati")
        self.horizontalLayout.addWidget(self.indica_ckLayerAbilitati)
        self.indica_ckSerieStorica = QtWidgets.QCheckBox(self.horizontalLayout_check_indica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indica_ckSerieStorica.sizePolicy().hasHeightForWidth())
        self.indica_ckSerieStorica.setSizePolicy(sizePolicy)
        self.indica_ckSerieStorica.setObjectName("indica_ckSerieStorica")
        self.horizontalLayout.addWidget(self.indica_ckSerieStorica)
        self.horizontalLayout_8.addWidget(self.horizontalLayout_check_indica)
        self.horizontalLayout_funzioni_indica = QtWidgets.QGroupBox(self.tabIndica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLayout_funzioni_indica.sizePolicy().hasHeightForWidth())
        self.horizontalLayout_funzioni_indica.setSizePolicy(sizePolicy)
        self.horizontalLayout_funzioni_indica.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalLayout_funzioni_indica.setObjectName("horizontalLayout_funzioni_indica")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayout_funzioni_indica)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.indica_btDeseleziona = QtWidgets.QPushButton(self.horizontalLayout_funzioni_indica)
        self.indica_btDeseleziona.setMinimumSize(QtCore.QSize(0, 25))
        self.indica_btDeseleziona.setObjectName("indica_btDeseleziona")
        self.horizontalLayout_7.addWidget(self.indica_btDeseleziona)
        self.horizontalLayout_8.addWidget(self.horizontalLayout_funzioni_indica)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabIndica, "")
        self.tabCSW = QtWidgets.QWidget()
        self.tabCSW.setEnabled(True)
        self.tabCSW.setObjectName("tabCSW")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabCSW)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_13 = QtWidgets.QLabel(self.tabCSW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_26.addWidget(self.label_13)
        self.csw_cboCategory = QtWidgets.QComboBox(self.tabCSW)
        self.csw_cboCategory.setObjectName("csw_cboCategory")
        self.horizontalLayout_26.addWidget(self.csw_cboCategory)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_14 = QtWidgets.QLabel(self.tabCSW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(50, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_25.addWidget(self.label_14)
        self.csw_txFiltro = QtWidgets.QLineEdit(self.tabCSW)
        self.csw_txFiltro.setObjectName("csw_txFiltro")
        self.horizontalLayout_25.addWidget(self.csw_txFiltro)
        self.csw_btCerca = QtWidgets.QPushButton(self.tabCSW)
        self.csw_btCerca.setAutoDefault(False)
        self.csw_btCerca.setObjectName("csw_btCerca")
        self.horizontalLayout_25.addWidget(self.csw_btCerca)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.csw_btApriAlbero = QtWidgets.QPushButton(self.tabCSW)
        self.csw_btApriAlbero.setObjectName("csw_btApriAlbero")
        self.horizontalLayout_24.addWidget(self.csw_btApriAlbero)
        self.csw_btChiudiAlbero = QtWidgets.QPushButton(self.tabCSW)
        self.csw_btChiudiAlbero.setObjectName("csw_btChiudiAlbero")
        self.horizontalLayout_24.addWidget(self.csw_btChiudiAlbero)
        self.csw_btMetadati = QtWidgets.QPushButton(self.tabCSW)
        self.csw_btMetadati.setObjectName("csw_btMetadati")
        self.horizontalLayout_24.addWidget(self.csw_btMetadati)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.csw_treeWidget = QtWidgets.QTreeWidget(self.tabCSW)
        self.csw_treeWidget.setHeaderHidden(True)
        self.csw_treeWidget.setObjectName("csw_treeWidget")
        self.csw_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_10.addWidget(self.csw_treeWidget)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabCSW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.csw_groupedCheck = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csw_groupedCheck.sizePolicy().hasHeightForWidth())
        self.csw_groupedCheck.setSizePolicy(sizePolicy)
        self.csw_groupedCheck.setObjectName("csw_groupedCheck")
        self.horizontalLayout_16.addWidget(self.csw_groupedCheck)
        self.csw_ckLayerAbilitati = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csw_ckLayerAbilitati.sizePolicy().hasHeightForWidth())
        self.csw_ckLayerAbilitati.setSizePolicy(sizePolicy)
        self.csw_ckLayerAbilitati.setMinimumSize(QtCore.QSize(110, 0))
        self.csw_ckLayerAbilitati.setChecked(False)
        self.csw_ckLayerAbilitati.setObjectName("csw_ckLayerAbilitati")
        self.horizontalLayout_16.addWidget(self.csw_ckLayerAbilitati)
        self.csw_ckDescrizione = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csw_ckDescrizione.sizePolicy().hasHeightForWidth())
        self.csw_ckDescrizione.setSizePolicy(sizePolicy)
        self.csw_ckDescrizione.setObjectName("csw_ckDescrizione")
        self.horizontalLayout_16.addWidget(self.csw_ckDescrizione)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tabCSW, "")
        self.tabConf = QtWidgets.QWidget()
        self.tabConf.setObjectName("tabConf")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabConf)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 9, 415, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_4.setObjectName("groupBox_4")
        self.conf_chkLocale = QtWidgets.QCheckBox(self.groupBox_4)
        self.conf_chkLocale.setGeometry(QtCore.QRect(30, 20, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_chkLocale.sizePolicy().hasHeightForWidth())
        self.conf_chkLocale.setSizePolicy(sizePolicy)
        self.conf_chkLocale.setObjectName("conf_chkLocale")
        self.conf_btnAbout = QtWidgets.QPushButton(self.groupBox_4)
        self.conf_btnAbout.setGeometry(QtCore.QRect(280, 0, 92, 48))
        self.conf_btnAbout.setMinimumSize(QtCore.QSize(80, 40))
        self.conf_btnAbout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/csiatlante/icons/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conf_btnAbout.setIcon(icon)
        self.conf_btnAbout.setIconSize(QtCore.QSize(80, 40))
        self.conf_btnAbout.setObjectName("conf_btnAbout")
        self.groupBoxServiceConnections = QtWidgets.QGroupBox(self.tabConf)
        self.groupBoxServiceConnections.setGeometry(QtCore.QRect(9, 55, 415, 116))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxServiceConnections.sizePolicy().hasHeightForWidth())
        self.groupBoxServiceConnections.setSizePolicy(sizePolicy)
        self.groupBoxServiceConnections.setObjectName("groupBoxServiceConnections")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxServiceConnections)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.label_15 = QtWidgets.QLabel(self.groupBoxServiceConnections)
        self.label_15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.conf_cboServiceConnections = QtWidgets.QComboBox(self.groupBoxServiceConnections)
        self.conf_cboServiceConnections.setMaximumSize(QtCore.QSize(300, 20))
        self.conf_cboServiceConnections.setObjectName("conf_cboServiceConnections")
        self.horizontalLayout_20.addWidget(self.conf_cboServiceConnections)
        self.gridLayout.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.conf_btnServiceNew = QtWidgets.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceNew.setObjectName("conf_btnServiceNew")
        self.horizontalLayout_18.addWidget(self.conf_btnServiceNew)
        self.conf_btnServiceEdit = QtWidgets.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceEdit.setObjectName("conf_btnServiceEdit")
        self.horizontalLayout_18.addWidget(self.conf_btnServiceEdit)
        self.conf_btnServiceDelete = QtWidgets.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceDelete.setObjectName("conf_btnServiceDelete")
        self.horizontalLayout_18.addWidget(self.conf_btnServiceDelete)
        self.gridLayout.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.conf_btnServiceSaveFile = QtWidgets.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceSaveFile.setObjectName("conf_btnServiceSaveFile")
        self.horizontalLayout_19.addWidget(self.conf_btnServiceSaveFile)
        self.conf_btnServiceLoadFile = QtWidgets.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceLoadFile.setObjectName("conf_btnServiceLoadFile")
        self.horizontalLayout_19.addWidget(self.conf_btnServiceLoadFile)
        self.conf_btnServiceLoadDefault = QtWidgets.QPushButton(self.groupBoxServiceConnections)
        self.conf_btnServiceLoadDefault.setEnabled(False)
        self.conf_btnServiceLoadDefault.setObjectName("conf_btnServiceLoadDefault")
        self.horizontalLayout_19.addWidget(self.conf_btnServiceLoadDefault)
        self.gridLayout.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.groupBoxConnections = QtWidgets.QGroupBox(self.tabConf)
        self.groupBoxConnections.setGeometry(QtCore.QRect(9, 177, 411, 117))
        self.groupBoxConnections.setObjectName("groupBoxConnections")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxConnections)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.groupBoxConnections)
        self.label_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.conf_cboConnections = QtWidgets.QComboBox(self.groupBoxConnections)
        self.conf_cboConnections.setMaximumSize(QtCore.QSize(300, 20))
        self.conf_cboConnections.setObjectName("conf_cboConnections")
        self.horizontalLayout_22.addWidget(self.conf_cboConnections)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.conf_btnNew = QtWidgets.QPushButton(self.groupBoxConnections)
        self.conf_btnNew.setObjectName("conf_btnNew")
        self.horizontalLayout_27.addWidget(self.conf_btnNew)
        self.conf_btnEdit = QtWidgets.QPushButton(self.groupBoxConnections)
        self.conf_btnEdit.setObjectName("conf_btnEdit")
        self.horizontalLayout_27.addWidget(self.conf_btnEdit)
        self.conf_btnDelete = QtWidgets.QPushButton(self.groupBoxConnections)
        self.conf_btnDelete.setObjectName("conf_btnDelete")
        self.horizontalLayout_27.addWidget(self.conf_btnDelete)
        self.gridLayout_2.addLayout(self.horizontalLayout_27, 1, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.conf_btnSaveFile = QtWidgets.QPushButton(self.groupBoxConnections)
        self.conf_btnSaveFile.setObjectName("conf_btnSaveFile")
        self.horizontalLayout_28.addWidget(self.conf_btnSaveFile)
        self.conf_btnLoadFile = QtWidgets.QPushButton(self.groupBoxConnections)
        self.conf_btnLoadFile.setObjectName("conf_btnLoadFile")
        self.horizontalLayout_28.addWidget(self.conf_btnLoadFile)
        self.conf_btnLoadDefault = QtWidgets.QPushButton(self.groupBoxConnections)
        self.conf_btnLoadDefault.setEnabled(False)
        self.conf_btnLoadDefault.setObjectName("conf_btnLoadDefault")
        self.horizontalLayout_28.addWidget(self.conf_btnLoadDefault)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabConf, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btAggiorna = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btAggiorna.setObjectName("btAggiorna")
        self.horizontalLayout_6.addWidget(self.btAggiorna)
        self.btCarica = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btCarica.setObjectName("btCarica")
        self.horizontalLayout_6.addWidget(self.btCarica)
        self.btSvuotaToc = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btSvuotaToc.setObjectName("btSvuotaToc")
        self.horizontalLayout_6.addWidget(self.btSvuotaToc)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        CsiAtlante.setWidget(self.dockWidgetContents)

        self.retranslateUi(CsiAtlante)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(CsiAtlante)

    def retranslateUi(self, CsiAtlante):
        _translate = QtCore.QCoreApplication.translate
        CsiAtlante.setWindowTitle(_translate("CsiAtlante", "CSI Atlante"))
        self.label_10.setText(_translate("CsiAtlante", "Categoria"))
        self.label_9.setText(_translate("CsiAtlante", "Filtro"))
        self.prj_btCerca.setText(_translate("CsiAtlante", "Cerca"))
        self.prj_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto"))
        self.prj_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProgetti), _translate("CsiAtlante", "Progetti"))
        self.label_4.setText(_translate("CsiAtlante", "Categoria"))
        self.label_3.setText(_translate("CsiAtlante", "Filtro"))
        self.dati_btCerca.setText(_translate("CsiAtlante", "Cerca"))
        self.dati_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto"))
        self.dati_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto"))
        self.dati_btMetadati.setText(_translate("CsiAtlante", "Metadati"))
        self.groupBox.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC"))
        self.dati_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (più lento)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPostgis), _translate("CsiAtlante", "Vector"))
        self.label_36.setText(_translate("CsiAtlante", "Categoria"))
        self.label_37.setText(_translate("CsiAtlante", "Filtro"))
        self.raster_btCerca.setText(_translate("CsiAtlante", "Cerca"))
        self.raster_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto"))
        self.raster_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto"))
        self.raster_btMetadati.setText(_translate("CsiAtlante", "Metadati"))
        self.groupBox_9.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC"))
        self.raster_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (più lento)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRaster), _translate("CsiAtlante", "Raster"))
        self.wms_lbCategory.setText(_translate("CsiAtlante", "Categoria"))
        self.wms_lbFiltro.setText(_translate("CsiAtlante", "Filtro"))
        self.wms_btCerca.setText(_translate("CsiAtlante", "Cerca"))
        self.wms_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto"))
        self.wms_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto"))
        self.wms_btMetadati.setText(_translate("CsiAtlante", "Metadati"))
        self.wms_formatoLabel.setText(_translate("CsiAtlante", "Formato"))
        self.wms_crsLabel.setText(_translate("CsiAtlante", "CRS"))
        self.gBox_check_WMS.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC"))
        self.wms_groupedCheck.setText(_translate("CsiAtlante", "Separati in gruppo"))
        self.wms_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (+ lento)"))
        self.wms_ckDescrizione.setText(_translate("CsiAtlante", "Breve"))
        self.wms_ckStampabile.setText(_translate("CsiAtlante", "Stampabile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWMS), _translate("CsiAtlante", "Geoservizi"))
        self.indica_lbCategory.setText(_translate("CsiAtlante", "Categoria"))
        self.indica_lbUnita.setText(_translate("CsiAtlante", "Unità territoriale"))
        self.indica_lbPeriodicita.setText(_translate("CsiAtlante", "Periodicità"))
        self.indica_lbFiltro.setText(_translate("CsiAtlante", "Filtro"))
        self.indica_btCerca.setText(_translate("CsiAtlante", "Cerca"))
        self.indica_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto"))
        self.indica_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto"))
        self.indica_btMetadati.setText(_translate("CsiAtlante", "Metadati"))
        self.horizontalLayout_check_indica.setTitle(_translate("CsiAtlante", "Gestione visualizzazione indicatori"))
        self.indica_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (+ lento)"))
        self.indica_ckSerieStorica.setText(_translate("CsiAtlante", "Serie Storica"))
        self.horizontalLayout_funzioni_indica.setTitle(_translate("CsiAtlante", "Funzioni Indicatori"))
        self.indica_btDeseleziona.setText(_translate("CsiAtlante", "Deseleziona Nodi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIndica), _translate("CsiAtlante", "Indicatori"))
        self.label_13.setText(_translate("CsiAtlante", "Server"))
        self.label_14.setText(_translate("CsiAtlante", "Filtro"))
        self.csw_btCerca.setText(_translate("CsiAtlante", "Cerca"))
        self.csw_btApriAlbero.setText(_translate("CsiAtlante", "Espandi tutto"))
        self.csw_btChiudiAlbero.setText(_translate("CsiAtlante", "Racchiudi tutto"))
        self.csw_btMetadati.setText(_translate("CsiAtlante", "Metadati"))
        self.groupBox_3.setTitle(_translate("CsiAtlante", "Gestione caricamento livelli in TOC"))
        self.csw_groupedCheck.setText(_translate("CsiAtlante", "Separati in un gruppo"))
        self.csw_ckLayerAbilitati.setText(_translate("CsiAtlante", "Già visibili (più lento)"))
        self.csw_ckDescrizione.setText(_translate("CsiAtlante", "Descrizione breve"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCSW), _translate("CsiAtlante", "CSW"))
        self.groupBox_4.setTitle(_translate("CsiAtlante", "Comportamento"))
        self.conf_chkLocale.setText(_translate("CsiAtlante", "Fuori Linea (file locali)"))
        self.groupBoxServiceConnections.setTitle(_translate("CsiAtlante", "Connessioni Servizi"))
        self.label_15.setText(_translate("CsiAtlante", "<html><head/><body><p><span style=\" font-weight:600;\">In uso :</span></p></body></html>"))
        self.conf_btnServiceNew.setText(_translate("CsiAtlante", "Nuova"))
        self.conf_btnServiceEdit.setText(_translate("CsiAtlante", "Modifica"))
        self.conf_btnServiceDelete.setText(_translate("CsiAtlante", "Elimina"))
        self.conf_btnServiceSaveFile.setText(_translate("CsiAtlante", "Salva su file"))
        self.conf_btnServiceLoadFile.setText(_translate("CsiAtlante", "Carica da file"))
        self.conf_btnServiceLoadDefault.setText(_translate("CsiAtlante", "Carica Default"))
        self.groupBoxConnections.setTitle(_translate("CsiAtlante", "Portafoglio Connessioni DB"))
        self.label_17.setText(_translate("CsiAtlante", "Lista:"))
        self.conf_btnNew.setText(_translate("CsiAtlante", "Nuova"))
        self.conf_btnEdit.setText(_translate("CsiAtlante", "Modifica"))
        self.conf_btnDelete.setText(_translate("CsiAtlante", "Elimina"))
        self.conf_btnSaveFile.setText(_translate("CsiAtlante", "Salva su file"))
        self.conf_btnLoadFile.setText(_translate("CsiAtlante", "Carica da file"))
        self.conf_btnLoadDefault.setText(_translate("CsiAtlante", "Carica Default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConf), _translate("CsiAtlante", "Impostazioni"))
        self.btAggiorna.setText(_translate("CsiAtlante", "Aggiorna Cache"))
        self.btCarica.setText(_translate("CsiAtlante", "Carica"))
        self.btSvuotaToc.setText(_translate("CsiAtlante", "Ripulisci Dati TOC"))

