# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_newconnection.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewConnectionDialog(object):
    def setupUi(self, NewConnectionDialog):
        NewConnectionDialog.setObjectName("NewConnectionDialog")
        NewConnectionDialog.resize(329, 332)
        self.layoutWidget = QtWidgets.QWidget(NewConnectionDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 23, 261, 164))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.leName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leName.setEnabled(False)
        self.leName.setObjectName("leName")
        self.horizontalLayout.addWidget(self.leName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.leHost = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leHost.setObjectName("leHost")
        self.horizontalLayout_2.addWidget(self.leHost)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lePort = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lePort.setObjectName("lePort")
        self.horizontalLayout_3.addWidget(self.lePort)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.leDatabase = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leDatabase.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leDatabase.setObjectName("leDatabase")
        self.horizontalLayout_4.addWidget(self.leDatabase)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.leUsername = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leUsername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leUsername.setObjectName("leUsername")
        self.horizontalLayout_5.addWidget(self.leUsername)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lePassword = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setObjectName("lePassword")
        self.horizontalLayout_6.addWidget(self.lePassword)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(NewConnectionDialog)
        self.buttonBox.accepted.connect(NewConnectionDialog.accept)
        self.buttonBox.rejected.connect(NewConnectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewConnectionDialog)

    def retranslateUi(self, NewConnectionDialog):
        _translate = QtCore.QCoreApplication.translate
        NewConnectionDialog.setWindowTitle(_translate("NewConnectionDialog", "Crea una nuova connessione ad un db postgre"))
        self.groupBox.setTitle(_translate("NewConnectionDialog", "Dettagli della connessione DB"))
        self.label.setText(_translate("NewConnectionDialog", "Nome"))
        self.label_2.setText(_translate("NewConnectionDialog", "Host"))
        self.label_3.setText(_translate("NewConnectionDialog", "Port"))
        self.label_4.setText(_translate("NewConnectionDialog", "Database"))
        self.label_5.setText(_translate("NewConnectionDialog", "Username"))
        self.label_6.setText(_translate("NewConnectionDialog", "Password"))

